### ISSUE TITLE
Out of memory when getting screenshot

### ISSUE THREAD

**Issue by Jamesits** [Jamesits/ScreenShooter#1]
```
Nov 09 03:29:48 ScreenShooterBot dotnet[17499]: 2018-11-09 03:29:48.1207|DEBUG|TelegramBotConnector|Received message from @Jamesits: https://mp.weixin.qq.com/s/rlezp4LrtuRd_BXx2Q9uhA
Nov 09 03:29:48 ScreenShooterBot dotnet[17499]: 2018-11-09 03:29:48.4920|DEBUG|Program|Creating session 85ead73d-74e5-4afd-a720-2086e5f1fc7b
Nov 09 03:29:48 ScreenShooterBot dotnet[17499]: 2018-11-09 03:29:48.4920|DEBUG|HeadlessChromeActuator|Enter CapturePage() for session 85ead73d-74e5-4afd-a720-2086e5f1fc7b
Nov 09 03:29:48 ScreenShooterBot dotnet[17499]: 2018-11-09 03:29:48.4944|DEBUG|HeadlessChromeActuator|Create incognito session
Nov 09 03:29:48 ScreenShooterBot dotnet[17499]: 2018-11-09 03:29:48.4944|DEBUG|HeadlessChromeActuator|Create new tab
Nov 09 03:29:48 ScreenShooterBot dotnet[17499]: 2018-11-09 03:29:48.6516|DEBUG|HeadlessChromeActuator|Navigate to "https://mp.weixin.qq.com/s/rlezp4LrtuRd_BXx2Q9uhA"
Nov 09 03:29:51 ScreenShooterBot dotnet[17499]: 2018-11-09 03:29:51.2201|DEBUG|HeadlessChromeActuator|Trying to load lazy-loading elements
Nov 09 03:30:51 ScreenShooterBot dotnet[17499]: 2018-11-09 03:30:51.3865|DEBUG|HeadlessChromeActuator|Taking screenshot
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: [1109/033057.983772:INFO:SkBitmap.h(515)] ../../third_party/skia/include/core/SkBitmap.h:515: fatal error: "assert(this->tryAllocPixels(info, rowBytes))"
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: Received signal 6
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: #0 0x56529abaacac base::debug::StackTrace::StackTrace()
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: #1 0x56529abaa821 base::debug::(anonymous namespace)::StackDumpSignalHandler()
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: #2 0x7fef4ea7e890 <unknown>
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: #3 0x7fef48826e97 gsignal
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: #4 0x7fef48828801 abort
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: #5 0x56529ada5985 sk_abort_no_print()
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: #6 0x56529bea8c17 viz::SoftwareRenderer::CopyDrawnRenderPass()
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: #7 0x56529be6e84a viz::DirectRenderer::DrawRenderPassAndExecuteCopyRequests()
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: #8 0x56529be6e4b1 viz::DirectRenderer::DrawFrame()
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: #9 0x56529be6a56c viz::Display::DrawAndSwap()
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: #10 0x56529be7a0c3 viz::DisplayScheduler::DrawAndSwap()
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: #11 0x56529be7926c viz::DisplayScheduler::OnBeginFrameDeadline()
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: #12 0x56529ab29929 base::debug::TaskAnnotator::RunTask()
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: #13 0x56529ab28d0e base::MessageLoop::RunTask()
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: #14 0x56529ab290a2 base::MessageLoop::DoWork()
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: #15 0x56529ab2b909 base::MessagePumpGlib::Run()
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: #16 0x56529ab47155 base::RunLoop::Run()
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: #17 0x565299641154 content::BrowserMainLoop::MainMessageLoopRun()
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: #18 0x565299640f13 content::BrowserMainLoop::RunMainMessageLoopParts()
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: #19 0x565299643b82 content::BrowserMainRunnerImpl::Run()
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: #20 0x56529ecc6ccf headless::HeadlessContentMainDelegate::RunProcess()
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: #21 0x56529a7ee22d content::ContentMainRunnerImpl::Run()
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: #22 0x56529a8214eb service_manager::Main()
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: #23 0x56529a7ec5c1 content::ContentMain()
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: #24 0x56529ecc5ae8 headless::(anonymous namespace)::RunContentMain()
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: #25 0x56529ecc5b78 headless::HeadlessBrowserMain()
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: #26 0x56529a81e9db headless::HeadlessShellMain()
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: #27 0x565298b2c1ac ChromeMain
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: #28 0x7fef48809b97 __libc_start_main
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: #29 0x565298b2c02a _start
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]:   r8: 0000000000000000  r9: 00007fffd46a19a0 r10: 0000000000000008 r11: 0000000000000246
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]:  r12: 0000000000000000 r13: 00007fffd46a1c80 r14: 00007fffd46a1d30 r15: 00001f77fa479500
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]:   di: 0000000000000002  si: 00007fffd46a19a0  bp: 00007fffd46a1bf0  bx: 0000000000000780
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]:   dx: 0000000000000000  ax: 0000000000000000  cx: 00007fef48826e97  sp: 00007fffd46a19a0
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]:   ip: 00007fef48826e97 efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]:  trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: [end of stack trace]
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: Calling _exit(1). Core file will not be generated.
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: 2018-11-09 03:30:58.5595|ERROR|Program|Something happened.
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: Exception:
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: PuppeteerSharp.TargetClosedException: Protocol error(Page.captureScreenshot): Target closed.
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]:    at PuppeteerSharp.CDPSession.SendAsync(String method, Object args, Boolean waitForCallback)
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]:    at CallSite.Target(Closure , CallSite , Object )
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]:    at PuppeteerSharp.CDPSession.SendAsync[T](String method, Object args)
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]:    at CallSite.Target(Closure , CallSite , Object )
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]:    at PuppeteerSharp.Page.PerformScreenshot(ScreenshotType type, ScreenshotOptions options)
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]:    at PuppeteerSharp.Helpers.TaskQueue.Enqueue[T](Func`1 taskGenerator)
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]:    at PuppeteerSharp.Page.ScreenshotDataAsync(ScreenshotOptions options)
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]:    at PuppeteerSharp.Page.ScreenshotAsync(String file, ScreenshotOptions options)
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]:    at ScreenShooter.Actuator.HeadlessChromeActuator.CapturePage(String url, Guid sessionId) in /home/vsts/work/1/s/ScreenShooter.Actuator/HeadlessChromeActuator.cs:line 122
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]:    at ScreenShooter.Program.Connect(Object sender, EventArgs e) in /home/vsts/work/1/s/ScreenShooter/Program.cs:line 162
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: InnerException:
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: 2018-11-09 03:30:58.5634|DEBUG|TelegramBotConnector|Sending session information
Nov 09 03:30:58 ScreenShooterBot dotnet[17499]: 2018-11-09 03:30:58.9464|DEBUG|Program|Ending session 85ead73d-74e5-4afd-a720-2086e5f1fc7b
```

Then `_browser.IsClosed == false` but

```
Nov 09 04:02:25 ScreenShooterBot dotnet[19287]: ERROR|HeadlessChromeActuator|Something happened.
Nov 09 04:02:25 ScreenShooterBot dotnet[19287]: Exception:
Nov 09 04:02:25 ScreenShooterBot dotnet[19287]: PuppeteerSharp.TargetClosedException: Protocol error(Page.printToPDF): Target closed.
Nov 09 04:02:25 ScreenShooterBot dotnet[19287]:    at PuppeteerSharp.CDPSession.SendAsync(String method, Object args, Boolean waitForCallback)
Nov 09 04:02:25 ScreenShooterBot dotnet[19287]:    at PuppeteerSharp.Page.PdfDataAsync(PdfOptions options)
Nov 09 04:02:25 ScreenShooterBot dotnet[19287]:    at PuppeteerSharp.Page.PdfAsync(String file, PdfOptions options)
Nov 09 04:02:25 ScreenShooterBot dotnet[19287]:    at ScreenShooter.Actuator.HeadlessChromeActuator.CapturePage(String url, Guid sessionId) in /home/vsts/work/1/s/ScreenShooter.Actuator/HeadlessChromeActuator.cs:line 152
Nov 09 04:02:25 ScreenShooterBot dotnet[19287]: InnerException:
Nov 09 04:02:25 ScreenShooterBot dotnet[19287]: DEBUG|HeadlessChromeActuator|Taking screenshot
Nov 09 04:02:25 ScreenShooterBot dotnet[19287]: ERROR|Program|Something happened.
Nov 09 04:02:25 ScreenShooterBot dotnet[19287]: Exception:
Nov 09 04:02:25 ScreenShooterBot dotnet[19287]: PuppeteerSharp.MessageException: Protocol error(Target.sendMessageToTarget): Target closed. ---> PuppeteerSharp.TargetClosedException: Protocol error(Target.sendMessageToTarget): Target closed.
Nov 09 04:02:25 ScreenShooterBot dotnet[19287]:    at PuppeteerSharp.Connection.SendAsync(String method, Object args, Boolean waitForCallback)
Nov 09 04:02:25 ScreenShooterBot dotnet[19287]:    at PuppeteerSharp.CDPSession.SendAsync(String method, Object args, Boolean waitForCallback)
Nov 09 04:02:25 ScreenShooterBot dotnet[19287]:    --- End of inner exception stack trace ---
Nov 09 04:02:25 ScreenShooterBot dotnet[19287]:    at PuppeteerSharp.CDPSession.SendAsync(String method, Object args, Boolean waitForCallback)
Nov 09 04:02:25 ScreenShooterBot dotnet[19287]:    at PuppeteerSharp.Page.PerformScreenshot(ScreenshotType type, ScreenshotOptions options)
Nov 09 04:02:25 ScreenShooterBot dotnet[19287]:    at PuppeteerSharp.Helpers.TaskQueue.Enqueue[T](Func`1 taskGenerator)
Nov 09 04:02:25 ScreenShooterBot dotnet[19287]:    at PuppeteerSharp.Page.ScreenshotDataAsync(ScreenshotOptions options)
Nov 09 04:02:25 ScreenShooterBot dotnet[19287]:    at PuppeteerSharp.Page.ScreenshotAsync(String file, ScreenshotOptions options)
Nov 09 04:02:25 ScreenShooterBot dotnet[19287]:    at ScreenShooter.Actuator.HeadlessChromeActuator.CapturePage(String url, Guid sessionId) in /home/vsts/work/1/s/ScreenShooter.Actuator/HeadlessChromeActuator.cs:line 169
Nov 09 04:02:25 ScreenShooterBot dotnet[19287]:    at ScreenShooter.Program.Connect(Object sender, EventArgs e) in /home/vsts/work/1/s/ScreenShooter/Program.cs:line 162
Nov 09 04:02:25 ScreenShooterBot dotnet[19287]: InnerException:PuppeteerSharp.TargetClosedException: Protocol error(Target.sendMessageToTarget): Target closed.
Nov 09 04:02:25 ScreenShooterBot dotnet[19287]:    at PuppeteerSharp.Connection.SendAsync(String method, Object args, Boolean waitForCallback)
Nov 09 04:02:25 ScreenShooterBot dotnet[19287]:    at PuppeteerSharp.CDPSession.SendAsync(String method, Object args, Boolean waitForCallback)
Nov 09 04:02:25 ScreenShooterBot dotnet[19287]: DEBUG|TelegramBotConnector|Sending session information
Nov 09 04:02:25 ScreenShooterBot dotnet[19287]: DEBUG|Program|Ending session 8fe4b3d6-9ccd-42bd-90b6-52b4fa6dd6a9
```

**Comment by Jamesits** [comment]
reported to upstream https://github.com/kblok/puppeteer-sharp/issues/749

**Comment by Jamesits** [comment]
fixed by enabling swap
